### ISSUE TITLE
1.17.1 fabric backport?

### ISSUE THREAD

**Issue by the-just-luke** [Keksuccino/Panoramica#1]
On curseforge only 1.16.5, 1.18.1/2, and 1.19.2 are available, skipping 1.17 which still has an active player base.

**Comment by Keksuccino** [comment]
1.17 Fabric has no active player base and I will not release mods for 1.17 anymore, sorry. Even 1.16 Fabric has no active player base anymore. The version of Panoramica for 1.16 is older from when there was still a big player base.
