### ISSUE TITLE
[Feature Request] Make this mod respect F1

### ISSUE THREAD

**Issue by TBlazeWarriorT** [Keksuccino/Panoramica#10]
So, this mod is going to have a million incompatibilities with literally anything being rendered on the screen that we don't want. This includes waypoints, FPS counters, potion effects... If this mod doesn't respect F1 (Minecraft's keybind to hide the UI) somehow when taking the panorama, this mod will be a nightmare to use... This mod seems to force F1 mode to off whenever taking the panorama, it's so sad... A big improvement suggestion will be if you can make this mod access the F1 UI hiding and respect it, thanks.

**Comment by TBlazeWarriorT** [comment]
Example of a silly panorama image taken because of this:
![panorama_0](https://github.com/Keksuccino/Panoramica/assets/25572454/8e06c831-573f-4e3f-83ab-2fa7c01ad88c)

**Comment by erlandyt** [comment]
I am having the same problem

**Comment by Keksuccino** [comment]
Could be fixed in Panoramica v1.3.0! If it still happens, please open a new issue, thank you very much!
