### ISSUE TITLE
[Suggestion] Automatic screenshots on exit

### ISSUE THREAD

**Issue by RSS90** [Keksuccino/Panoramica#16]
Hello, would it be possible to add a function that allows you to take panorama screenshots when you leave the game in combination with FancyMenu?

The idea behind it: As soon as you leave the game, a panorama is created that captures the player's last point of view. These images are written directly into a preconfigured FancyMenu panorama and replaced. This would allow new layout panoramas to be created each time, showing the player his own environment.

Maybe an implementation of the automatic detection of the pixel height so that unnecessarily large images are not generated and if this makes sense in terms of performance or at all, a distance measurement of the last block where the player looks to calculate a dynamic FOV for the panormana.

I think this would be an interesting possibility for modpack creators, it just depends on whether this is wanted :D

**Comment by Keksuccino** [comment]
Will not happen, sorry. Then the player would rotate every time they leave the game (to create the screenshot).

**Comment by RSS90** [comment]
Ok thought that would be bearable. But thanks for the answer anyway :D

**Comment by mpustovoi** [comment]
You can use [Seamless Loading Screen](https://modrinth.com/mod/seamless-loading-screen) mod.
It's not the same, but it's the closest thing to what you're asking for.
