### ISSUE TITLE
Latest 1.19.2 Fabric Release only takes FULL WHITE screenshots.

### ISSUE THREAD

**Issue by TheFantasticLoki** [Keksuccino/Panoramica#2]
I updated panoramica after seeing the latest improvements but after attempting to use it all my screenshots appear pure white and my character no longer looks around to take the pictures.

**Comment by Keksuccino** [comment]
Remove OptiFine and similar mods when taking screenshots, then it should work :)

**Comment by TheFantasticLoki** [comment]
I use iris and I would rather not. That's why I take the panorama's in the first place is to have nice shader screenshots for the main menus.

**Comment by Keksuccino** [comment]
Panoramica v1.2.1 should fix this! Thank you for your report!
