### ISSUE TITLE
| Fabric 1.19.2 | Incompatible with the "Blur" mod from Motschen

### ISSUE THREAD

**Issue by szunakabeats** [Keksuccino/Panoramica#3]
When taking screenshots with the Blur mod installed the blur activates after pressing 'R' 

With Blur installed:
![panorama_2](https://user-images.githubusercontent.com/88375166/194360983-ebbbfeb6-6801-4162-92ea-7e9246c1f22d.png)

With Blur Removed (same Modpack):

![panorama_2](https://user-images.githubusercontent.com/88375166/194361180-fef4dcc6-485c-413f-afb7-9852c0dce22e.png)

**Comment by Keksuccino** [comment]
I can't fix this on my end I think. The author of the other mod would need to exclude `de.keksuccino.panoramica.DummyScreen`, so it doesn't get blurred anymore.

**Comment by szunakabeats** [comment]
okay thx for letting me know! i saw a config option in the Blur mod which allows for gui exclusions :) so i fixed it ! 

but maybe u can let people know in the panoramic mod description that when using mods which modify gui's that they can exclude yours using 

> de.keksuccino.panoramica.DummyScreen

also btw best panorama mod out there !
