### ISSUE TITLE
| Fabric 1.19.2 | Status effect icons appear on panoramas

### ISSUE THREAD

**Issue by szunakabeats** [Keksuccino/Panoramica#4]
Not a huge bug, but i wanted to let u know :)

also im using "Mini Effects" from Snownee_ maybe thats incompatible ?

Panorama:
![panorama_1](https://user-images.githubusercontent.com/88375166/194371519-bf3720a3-c1f0-45bf-a658-7a8f9cd14180.png)

Result (its tracked on the ground? xd) :
![funny bug](https://user-images.githubusercontent.com/88375166/194371570-795ea56d-b95c-438f-9ac2-7121e2b0dc7a.png)

**Comment by Keksuccino** [comment]
The mod hides the HUD, so all mod HUDs should be hidden too. Are the mod icons hidden when you hide the HUD normally?

**Comment by szunakabeats** [comment]
what do you mean with normaly ? it's hidden when hiding the gui with 'F1' like in the first picture above

the effect comes from the [Ecologics](https://www.curseforge.com/minecraft/mc-mods/ecologics) mod

thx for the quick answer !

**Comment by Keksuccino** [comment]
Could be fixed in Panoramica v1.3.0! If it still happens, please open a new issue, thank you very much!
