### ISSUE TITLE
(Forge 1.18.2) Chat Gets Un-Hidden When Taking a Panorama

### ISSUE THREAD

**Issue by Toastr125** [Keksuccino/Panoramica#7]
Chat messages show up in the panorama images. Even if F1 is used to hide the UI prior to taking them, recent chat messages will still show up in the images. Just waiting for them to go away isn't a great option because it prevents the player from using commands to stage a particular moment to capture. Additionally, I don't see why you would ever want chat to be shown in a panorama in the first place.

Panoramica version: 1.2.1

**Comment by Keksuccino** [comment]
Could be fixed in Panoramica v1.3.0! If it still happens, please open a new issue, thank you very much!
